### ISSUE TITLE
Single character column names

### ISSUE THREAD

**Issue by Rhidlor** [markdirish/node-odbc#112]
_As of the submission of this issue I am using the latest version of this package._ 
When I perform a SELECT query on my IBM Db2 database it returns only the first character of the column name.

```js
app.get("/getNegatives", function (req, res, next) {
	odbc.connect(process.env.CONN_STR, (err, conn) => {
		if (err) return console.log(err);
		conn.query(`SELECT B4CONB AS PRODNUM, B4C2QT AS STOCK FROM PRODSTOCK WHERE B4C2QT<0 AND B4BKCD='STORL1' ORDER BY B4C2QT ASC`, (err, data) => {
			conn.close((err) => {
				if (err) return console.log(err);
				res.send(data);
			});
		});
	});
});
```
```json
[
  {
    "P": 289233,
    "S": -71
  },
  {
    "P": 289240,
    "S": -63
  },
  {
    "P": 2987008,
    "S": -53
  }
]
```

_This is the first time I've created an issue on a GitHub repository so forgive me if I'm doing something wrong._

**Comment by markdirish** [comment]
Huh. Didn't think I touched that code in the latest patch. Was it working ok before?

I have today off, but I could maybe take a look tonight (US Central Time). Most likely get a fix out tomorrow.

**Comment by kadler** [comment]
@Rhidlor are you running on Windows?

If so, @markdirish this could be related to enabling UNICODE. If we were treating a string as UTF-8 and feeding it UTF-16LE could produce this result. eg. "ABCD" in UTF-16LE is x'4100420043004400' and passing that to an API that expects a null-terminated string it treats the second byte of the UTF-16 code point as the null-terminator.

**Comment by markdirish** [comment]
https://github.com/markdirish/node-odbc/blob/ed4fbedcd42e5d690ab9e21ccd68e31a2fb81031/src/odbc_connection.cpp#L317-L323

Looks likely, the code always assumes UTF-8 when translating to Napi::String::New.

https://github.com/nodejs/node-addon-api/blob/master/napi-inl.h#L786

It looks like I will have to cast them as `char16_t`s if `UNICODE` is defined

**Comment by Rhidlor** [comment]
Sorry for the late reply, I didn't have this issue before the latest patch, and yes my development environment is on Windows.

**Comment by citolen** [comment]
@markdirish Additionally when translating `ODBCError` to `Napi::Object` the same issue occurs.
Meaning error messages are also truncated.

i.e
```
[Error: [odbc] Error executing the sql statement] {
  odbcErrors: [ { state: '4', code: -131, message: '[' } ]
}
```

As you said casting to `char16_t` when `UNICODE` is defined solves the problem.

**Comment by wesbelonci** [comment]
same problem

**Comment by markdirish** [comment]
Getting a change out soon. As a temporary fix, you can remove `UNICODE` from the defines in `binding.gyp` and recompile with `npm install --build-from-source`, or you can downgrade to version `2.3.1`

**Comment by markdirish** [comment]
Ok, 2.3.3 should now be live, and there is a prebuilt win32-64bit binary. Let me know if it still looks broken (I tested before and after on a Windows system and it seemed fixed with these changed)

**Comment by reetp1dev** [comment]
I'm still getting single character column name with v2.3.3

![image](https://user-images.githubusercontent.com/59793526/89419974-b78bc480-d74f-11ea-84e1-2cfad9f15a8c.png)

**Comment by reetp1dev** [comment]
> I'm still getting single character column name with v2.3.3
> 
> ![image](https://user-images.githubusercontent.com/59793526/89419974-b78bc480-d74f-11ea-84e1-2cfad9f15a8c.png)

I downgraded to v.2.3.1 and it fixed the issue. 
![image](https://user-images.githubusercontent.com/59793526/89420824-e0608980-d750-11ea-8ae6-3cfe81f0f92c.png)

**Comment by YisaHsu** [comment]
I'm still getting single character column name with v2.3.3, too.

**Comment by markdirish** [comment]
Will look into this today, hopefully to get a (working) fix out by end of day

**Comment by markdirish** [comment]
Im a goofball. I fixed the `columns` property on the result, but not the actual column names in the result objects (or the statement). Was an easy fix, looking to push a fix tonight.

**Comment by YisaHsu** [comment]
I am an engineer working in a software development company.
My client (a company that uses Db2 for i5) went for summer vacation,
So it will take two weeks for me to work, so I'm sorry, 
but can only ask other users to report whether the problem has been solved?

**Comment by markdirish** [comment]
Should be fixed on version 2.3.4, available now on NPM.
